version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres # pulling image from dockerhub
    restart: always # restart the db if it fails
    ports:
      - 5432:5432 # mapping host port to container port; gives access to the container from localhost
    environment: # set environment variables including user, password and database name
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  pgadmin: # GUI interface to manage and control databbase, web-based service running on port 80
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: # set up username and password to access the interface
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  
  app:
    container_name: app
    build: . # build image using the dockerfile in the current directory
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always